/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class AccountStorageInfo (

    @SerialName(value = "used_cells")
    val usedCells: kotlin.Long,

    @SerialName(value = "used_bits")
    val usedBits: kotlin.Long,

    @SerialName(value = "used_public_cells")
    val usedPublicCells: kotlin.Long,

    /* time of the last payment */
    @SerialName(value = "last_paid")
    val lastPaid: kotlin.Long,

    @SerialName(value = "due_payment")
    val duePayment: kotlin.Long

) {


}

