/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.Action

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class AccountEvent (

    @SerialName(value = "event_id")
    val eventId: kotlin.String,

    @SerialName(value = "account")
    val account: AccountAddress,

    @SerialName(value = "timestamp")
    val timestamp: kotlin.Long,

    @SerialName(value = "actions")
    val actions: kotlin.collections.List<Action>,

    /* scam */
    @SerialName(value = "is_scam")
    val isScam: kotlin.Boolean,

    @SerialName(value = "lt")
    val lt: kotlin.Long,

    /* Event is not finished yet. Transactions still happening */
    @SerialName(value = "in_progress")
    val inProgress: kotlin.Boolean,

    /* TODO */
    @SerialName(value = "extra")
    val extra: kotlin.Long,

    @SerialName(value = "progress")
    val progress: kotlin.Float

) {


}

