/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class AccountAddress (

    @SerialName(value = "address")
    val address: kotlin.String,

    /* Is this account was marked as part of scammers activity */
    @SerialName(value = "is_scam")
    val isScam: kotlin.Boolean,

    @SerialName(value = "is_wallet")
    val isWallet: kotlin.Boolean,

    /* Display name. Data collected from different sources like moderation lists, dns, collections names and over. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "icon")
    val icon: kotlin.String? = null

) {


}

