/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountStatus
import io.tonapi.models.ExtraCurrency

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Account (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "balance")
    val balance: kotlin.Long,

    /* unix timestamp */
    @SerialName(value = "last_activity")
    val lastActivity: kotlin.Long,

    @Contextual @SerialName(value = "status")
    val status: AccountStatus,

    @SerialName(value = "get_methods")
    val getMethods: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "is_wallet")
    val isWallet: kotlin.Boolean,

    @SerialName(value = "extra_balance")
    val extraBalance: kotlin.collections.List<ExtraCurrency>? = null,

    /* {'USD': 1, 'IDR': 1000} */
    @Contextual @SerialName(value = "currencies_balance")
    val currenciesBalance: kotlin.collections.Map<kotlin.String, io.JsonAny>? = null,

    @SerialName(value = "interfaces")
    val interfaces: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "is_scam")
    val isScam: kotlin.Boolean? = null,

    @SerialName(value = "icon")
    val icon: kotlin.String? = null,

    @SerialName(value = "memo_required")
    val memoRequired: kotlin.Boolean? = null,

    @SerialName(value = "is_suspended")
    val isSuspended: kotlin.Boolean? = null

) {


}

