/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Auction (

    @SerialName(value = "domain")
    val domain: kotlin.String,

    @SerialName(value = "owner")
    val owner: kotlin.String,

    @SerialName(value = "price")
    val price: kotlin.Long,

    @SerialName(value = "bids")
    val bids: kotlin.Long,

    @SerialName(value = "date")
    val date: kotlin.Long

) {


}

