/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.Method
import io.tonapi.models.Source

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class BlockchainAccountInspect (

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "code_hash")
    val codeHash: kotlin.String,

    @SerialName(value = "methods")
    val methods: kotlin.collections.List<Method>,

    @SerialName(value = "compiler")
    val compiler: BlockchainAccountInspect.Compiler,

    @SerialName(value = "disassembled_code")
    val disassembledCode: kotlin.String? = null,

    @SerialName(value = "source")
    val source: Source? = null

) {

    /**
     * 
     *
     * Values: func,fift,tact.unknown
     */
    @Serializable(with = CompilerSerializer::class)
    enum class Compiler(val value: kotlin.String) {
        @SerialName(value = "func") func("func"),
        @SerialName(value = "fift") fift("fift"),
        @SerialName(value = "tact") tact("tact"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object CompilerSerializer : KSerializer<Compiler> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Compiler {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Compiler.entries.firstOrNull { it.value == value }
                ?: Compiler.unknown
        }

        override fun serialize(encoder: Encoder, value: Compiler) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

