/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class BlockchainConfig5 (

    @SerialName(value = "fee_burn_nom")
    val feeBurnNom: kotlin.Long,

    @SerialName(value = "fee_burn_denom")
    val feeBurnDenom: kotlin.Long,

    @SerialName(value = "blackhole_addr")
    val blackholeAddr: kotlin.String? = null

) {


}

