/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockchainConfig10
import io.tonapi.models.BlockchainConfig11
import io.tonapi.models.BlockchainConfig12
import io.tonapi.models.BlockchainConfig13
import io.tonapi.models.BlockchainConfig14
import io.tonapi.models.BlockchainConfig15
import io.tonapi.models.BlockchainConfig16
import io.tonapi.models.BlockchainConfig17
import io.tonapi.models.BlockchainConfig18
import io.tonapi.models.BlockchainConfig20
import io.tonapi.models.BlockchainConfig21
import io.tonapi.models.BlockchainConfig22
import io.tonapi.models.BlockchainConfig23
import io.tonapi.models.BlockchainConfig24
import io.tonapi.models.BlockchainConfig25
import io.tonapi.models.BlockchainConfig28
import io.tonapi.models.BlockchainConfig29
import io.tonapi.models.BlockchainConfig31
import io.tonapi.models.BlockchainConfig40
import io.tonapi.models.BlockchainConfig43
import io.tonapi.models.BlockchainConfig44
import io.tonapi.models.BlockchainConfig45
import io.tonapi.models.BlockchainConfig5
import io.tonapi.models.BlockchainConfig6
import io.tonapi.models.BlockchainConfig7
import io.tonapi.models.BlockchainConfig71
import io.tonapi.models.BlockchainConfig79
import io.tonapi.models.BlockchainConfig8
import io.tonapi.models.BlockchainConfig9
import io.tonapi.models.ValidatorsSet

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class BlockchainConfig (

    /* config boc in hex format */
    @SerialName(value = "raw")
    val raw: kotlin.String,

    /* config address */
    @SerialName(value = "0")
    val _0: kotlin.String,

    /* elector address */
    @SerialName(value = "1")
    val _1: kotlin.String,

    /* minter address */
    @SerialName(value = "2")
    val _2: kotlin.String,

    /* dns root address */
    @SerialName(value = "4")
    val _4: kotlin.String,

    @SerialName(value = "44")
    val _44: BlockchainConfig44,

    /* The address of the transaction fee collector. */
    @SerialName(value = "3")
    val _3: kotlin.String? = null,

    @SerialName(value = "5")
    val _5: BlockchainConfig5? = null,

    @SerialName(value = "6")
    val _6: BlockchainConfig6? = null,

    @SerialName(value = "7")
    val _7: BlockchainConfig7? = null,

    @SerialName(value = "8")
    val _8: BlockchainConfig8? = null,

    @SerialName(value = "9")
    val _9: BlockchainConfig9? = null,

    @SerialName(value = "10")
    val _10: BlockchainConfig10? = null,

    @SerialName(value = "11")
    val _11: BlockchainConfig11? = null,

    @SerialName(value = "12")
    val _12: BlockchainConfig12? = null,

    @SerialName(value = "13")
    val _13: BlockchainConfig13? = null,

    @SerialName(value = "14")
    val _14: BlockchainConfig14? = null,

    @SerialName(value = "15")
    val _15: BlockchainConfig15? = null,

    @SerialName(value = "16")
    val _16: BlockchainConfig16? = null,

    @SerialName(value = "17")
    val _17: BlockchainConfig17? = null,

    @SerialName(value = "18")
    val _18: BlockchainConfig18? = null,

    @SerialName(value = "20")
    val _20: BlockchainConfig20? = null,

    @SerialName(value = "21")
    val _21: BlockchainConfig21? = null,

    @SerialName(value = "22")
    val _22: BlockchainConfig22? = null,

    @SerialName(value = "23")
    val _23: BlockchainConfig23? = null,

    @SerialName(value = "24")
    val _24: BlockchainConfig24? = null,

    @SerialName(value = "25")
    val _25: BlockchainConfig25? = null,

    @SerialName(value = "28")
    val _28: BlockchainConfig28? = null,

    @SerialName(value = "29")
    val _29: BlockchainConfig29? = null,

    @SerialName(value = "31")
    val _31: BlockchainConfig31? = null,

    @SerialName(value = "32")
    val _32: ValidatorsSet? = null,

    @SerialName(value = "33")
    val _33: ValidatorsSet? = null,

    @SerialName(value = "34")
    val _34: ValidatorsSet? = null,

    @SerialName(value = "35")
    val _35: ValidatorsSet? = null,

    @SerialName(value = "36")
    val _36: ValidatorsSet? = null,

    @SerialName(value = "37")
    val _37: ValidatorsSet? = null,

    @SerialName(value = "40")
    val _40: BlockchainConfig40? = null,

    @SerialName(value = "43")
    val _43: BlockchainConfig43? = null,

    @SerialName(value = "45")
    val _45: BlockchainConfig45? = null,

    @SerialName(value = "71")
    val _71: BlockchainConfig71? = null,

    @SerialName(value = "72")
    val _72: BlockchainConfig71? = null,

    @SerialName(value = "73")
    val _73: BlockchainConfig71? = null,

    @SerialName(value = "79")
    val _79: BlockchainConfig79? = null,

    @SerialName(value = "81")
    val _81: BlockchainConfig79? = null,

    @SerialName(value = "82")
    val _82: BlockchainConfig79? = null

) {


}

