/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class BlockchainConfig17 (

    @SerialName(value = "min_stake")
    val minStake: kotlin.String,

    @SerialName(value = "max_stake")
    val maxStake: kotlin.String,

    @SerialName(value = "min_total_stake")
    val minTotalStake: kotlin.String,

    @SerialName(value = "max_stake_factor")
    val maxStakeFactor: kotlin.Long

) {


}

