/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountStatus
import io.tonapi.models.AccountStorageInfo
import io.tonapi.models.BlockchainRawAccountLibrariesInner
import io.tonapi.models.ExtraCurrency

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class BlockchainRawAccount (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "balance")
    val balance: kotlin.Long,

    @SerialName(value = "last_transaction_lt")
    val lastTransactionLt: kotlin.Long,

    @Contextual @SerialName(value = "status")
    val status: AccountStatus,

    @SerialName(value = "storage")
    val storage: AccountStorageInfo,

    @SerialName(value = "extra_balance")
    val extraBalance: kotlin.collections.List<ExtraCurrency>? = null,

    @SerialName(value = "code")
    val code: kotlin.String? = null,

    @SerialName(value = "data")
    val `data`: kotlin.String? = null,

    @SerialName(value = "last_transaction_hash")
    val lastTransactionHash: kotlin.String? = null,

    @SerialName(value = "frozen_hash")
    val frozenHash: kotlin.String? = null,

    @SerialName(value = "libraries")
    val libraries: kotlin.collections.List<BlockchainRawAccountLibrariesInner>? = null

) {


}

