/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockValueFlow

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class BlockchainBlock (

    @SerialName(value = "tx_quantity")
    val txQuantity: kotlin.Int,

    @SerialName(value = "value_flow")
    val valueFlow: BlockValueFlow,

    @SerialName(value = "workchain_id")
    val workchainId: kotlin.Int,

    @SerialName(value = "shard")
    val shard: kotlin.String,

    @SerialName(value = "seqno")
    val seqno: kotlin.Int,

    @SerialName(value = "root_hash")
    val rootHash: kotlin.String,

    @SerialName(value = "file_hash")
    val fileHash: kotlin.String,

    @SerialName(value = "global_id")
    val globalId: kotlin.Int,

    @SerialName(value = "version")
    val version: kotlin.Int,

    @SerialName(value = "after_merge")
    val afterMerge: kotlin.Boolean,

    @SerialName(value = "before_split")
    val beforeSplit: kotlin.Boolean,

    @SerialName(value = "after_split")
    val afterSplit: kotlin.Boolean,

    @SerialName(value = "want_split")
    val wantSplit: kotlin.Boolean,

    @SerialName(value = "want_merge")
    val wantMerge: kotlin.Boolean,

    @SerialName(value = "key_block")
    val keyBlock: kotlin.Boolean,

    @SerialName(value = "gen_utime")
    val genUtime: kotlin.Long,

    @SerialName(value = "start_lt")
    val startLt: kotlin.Long,

    @SerialName(value = "end_lt")
    val endLt: kotlin.Long,

    @SerialName(value = "vert_seqno")
    val vertSeqno: kotlin.Int,

    @SerialName(value = "gen_catchain_seqno")
    val genCatchainSeqno: kotlin.Int,

    @SerialName(value = "min_ref_mc_seqno")
    val minRefMcSeqno: kotlin.Int,

    @SerialName(value = "prev_key_block_seqno")
    val prevKeyBlockSeqno: kotlin.Int,

    @SerialName(value = "prev_refs")
    val prevRefs: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "in_msg_descr_length")
    val inMsgDescrLength: kotlin.Long,

    @SerialName(value = "out_msg_descr_length")
    val outMsgDescrLength: kotlin.Long,

    @SerialName(value = "rand_seed")
    val randSeed: kotlin.String,

    @SerialName(value = "created_by")
    val createdBy: kotlin.String,

    @SerialName(value = "gen_software_version")
    val genSoftwareVersion: kotlin.Int? = null,

    @SerialName(value = "gen_software_capabilities")
    val genSoftwareCapabilities: kotlin.Long? = null,

    @SerialName(value = "master_ref")
    val masterRef: kotlin.String? = null

) {


}

