/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: cskip_no_state,cskip_bad_state,cskip_no_gas,cskip_suspended.unknown
 */
@Serializable(with = ComputeSkipReasonSerializer::class)
enum class ComputeSkipReason(val value: kotlin.String) {

    @SerialName(value = "cskip_no_state")
    cskip_no_state("cskip_no_state"),

    @SerialName(value = "cskip_bad_state")
    cskip_bad_state("cskip_bad_state"),

    @SerialName(value = "cskip_no_gas")
    cskip_no_gas("cskip_no_gas"),

    @SerialName(value = "cskip_suspended")
    cskip_suspended("cskip_suspended"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ComputeSkipReason) "$data" else null

        /**
         * Returns a valid [ComputeSkipReason] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ComputeSkipReason? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object ComputeSkipReasonSerializer : KSerializer<ComputeSkipReason> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): ComputeSkipReason {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return ComputeSkipReason.entries.firstOrNull { it.value == value }
            ?: ComputeSkipReason.unknown
    }

    override fun serialize(encoder: Encoder, value: ComputeSkipReason) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

