/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: native,extra_currency,jetton,fiat.unknown
 */
@Serializable(with = CurrencyTypeSerializer::class)
enum class CurrencyType(val value: kotlin.String) {

    @SerialName(value = "native")
    native("native"),

    @SerialName(value = "extra_currency")
    extra_currency("extra_currency"),

    @SerialName(value = "jetton")
    jetton("jetton"),

    @SerialName(value = "fiat")
    fiat("fiat"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CurrencyType) "$data" else null

        /**
         * Returns a valid [CurrencyType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CurrencyType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object CurrencyTypeSerializer : KSerializer<CurrencyType> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): CurrencyType {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return CurrencyType.entries.firstOrNull { it.value == value }
            ?: CurrencyType.unknown
    }

    override fun serialize(encoder: Encoder, value: CurrencyType) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

