/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.DecodedMessageExtInMsgDecodedWalletHighloadV2
import io.tonapi.models.DecodedMessageExtInMsgDecodedWalletV3
import io.tonapi.models.DecodedMessageExtInMsgDecodedWalletV4
import io.tonapi.models.DecodedMessageExtInMsgDecodedWalletV5

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class DecodedMessageExtInMsgDecoded (

    @SerialName(value = "wallet_v3")
    val walletV3: DecodedMessageExtInMsgDecodedWalletV3? = null,

    @SerialName(value = "wallet_v4")
    val walletV4: DecodedMessageExtInMsgDecodedWalletV4? = null,

    @SerialName(value = "wallet_v5")
    val walletV5: DecodedMessageExtInMsgDecodedWalletV5? = null,

    @SerialName(value = "wallet_highload_v2")
    val walletHighloadV2: DecodedMessageExtInMsgDecodedWalletHighloadV2? = null

) {


}

