/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.DecodedRawMessage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class DecodedMessageExtInMsgDecodedWalletHighloadV2 (

    @SerialName(value = "subwallet_id")
    val subwalletId: kotlin.Long,

    @SerialName(value = "bounded_query_id")
    val boundedQueryId: kotlin.String,

    @SerialName(value = "raw_messages")
    val rawMessages: kotlin.collections.List<DecodedRawMessage>

) {


}

