/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class DomainBid (

    @SerialName(value = "success")
    val success: kotlin.Boolean = false,

    @SerialName(value = "value")
    val `value`: kotlin.Long,

    @SerialName(value = "txTime")
    val txTime: kotlin.Long,

    @SerialName(value = "txHash")
    val txHash: kotlin.String,

    @SerialName(value = "bidder")
    val bidder: AccountAddress

) {


}

