/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.Action
import io.tonapi.models.ValueFlow

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Event (

    @SerialName(value = "event_id")
    val eventId: kotlin.String,

    @SerialName(value = "timestamp")
    val timestamp: kotlin.Long,

    @SerialName(value = "actions")
    val actions: kotlin.collections.List<Action>,

    @SerialName(value = "value_flow")
    val valueFlow: kotlin.collections.List<ValueFlow>,

    /* scam */
    @SerialName(value = "is_scam")
    val isScam: kotlin.Boolean,

    @SerialName(value = "lt")
    val lt: kotlin.Long,

    /* Event is not finished yet. Transactions still happening */
    @SerialName(value = "in_progress")
    val inProgress: kotlin.Boolean,

    @SerialName(value = "progress")
    val progress: kotlin.Float

) {


}

