/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Data type of the argument value: - `nan`: Not-a-Number value - `null`: Null value - `tinyint`: Decimal integer (e.g., `100500`) - `int257`: 257-bit integer in hex format with 0x prefix (e.g., `0xfa01d78381ae32`) - `slice`: TON blockchain address (e.g., `0:6e731f2e...`) - `cell_boc_base64`: Base64-encoded cell BOC (Binary Object Code) (e.g., `te6ccgEBAQEAAgAAAA==`) - `slice_boc_hex`: Hex-encoded slice BOC (e.g., `b5ee9c72...`) 
 *
 * Values: nan,`null`,tinyint,int257,slice,cell_boc_base64,slice_boc_hex.unknown
 */
@Serializable(with = ExecGetMethodArgTypeSerializer::class)
enum class ExecGetMethodArgType(val value: kotlin.String) {

    @SerialName(value = "nan")
    nan("nan"),

    @SerialName(value = "null")
    `null`("null"),

    @SerialName(value = "tinyint")
    tinyint("tinyint"),

    @SerialName(value = "int257")
    int257("int257"),

    @SerialName(value = "slice")
    slice("slice"),

    @SerialName(value = "cell_boc_base64")
    cell_boc_base64("cell_boc_base64"),

    @SerialName(value = "slice_boc_hex")
    slice_boc_hex("slice_boc_hex"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ExecGetMethodArgType) "$data" else null

        /**
         * Returns a valid [ExecGetMethodArgType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ExecGetMethodArgType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object ExecGetMethodArgTypeSerializer : KSerializer<ExecGetMethodArgType> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): ExecGetMethodArgType {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return ExecGetMethodArgType.entries.firstOrNull { it.value == value }
            ?: ExecGetMethodArgType.unknown
    }

    override fun serialize(encoder: Encoder, value: ExecGetMethodArgType) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

