/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.TrustType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class FoundAccountsAddressesInner (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "preview")
    val preview: kotlin.String,

    @Contextual @SerialName(value = "trust")
    val trust: TrustType

) {


}

