/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class GasLimitPrices (

    @SerialName(value = "gas_price")
    val gasPrice: kotlin.Long,

    @SerialName(value = "gas_limit")
    val gasLimit: kotlin.Long,

    @SerialName(value = "gas_credit")
    val gasCredit: kotlin.Long,

    @SerialName(value = "block_gas_limit")
    val blockGasLimit: kotlin.Long,

    @SerialName(value = "freeze_due_limit")
    val freezeDueLimit: kotlin.Long,

    @SerialName(value = "delete_due_limit")
    val deleteDueLimit: kotlin.Long,

    @SerialName(value = "special_gas_limit")
    val specialGasLimit: kotlin.Long? = null,

    @SerialName(value = "flat_gas_limit")
    val flatGasLimit: kotlin.Long? = null,

    @SerialName(value = "flat_gas_price")
    val flatGasPrice: kotlin.Long? = null

) {


}

