/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.GaslessEstimateRequestMessagesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class GaslessEstimateRequest (

    @SerialName(value = "wallet_address")
    val walletAddress: kotlin.String,

    @SerialName(value = "wallet_public_key")
    val walletPublicKey: kotlin.String,

    @SerialName(value = "messages")
    val messages: kotlin.collections.List<GaslessEstimateRequestMessagesInner>,

    /* TONAPI verifies that the account has enough jettons to pay the commission and make a transfer. */
    @SerialName(value = "throw_error_if_not_enough_jettons")
    val throwErrorIfNotEnoughJettons: kotlin.Boolean? = false,

    @SerialName(value = "return_emulation")
    val returnEmulation: kotlin.Boolean? = false

) {


}

