/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.GetOutMsgQueueSizes200ResponseShardsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class GetOutMsgQueueSizes200Response (

    @SerialName(value = "ext_msg_queue_size_limit")
    val extMsgQueueSizeLimit: kotlin.Int,

    @SerialName(value = "shards")
    val shards: kotlin.collections.List<GetOutMsgQueueSizes200ResponseShardsInner>

) {


}

