/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param error 
 * @param errorCode 
 */
@Serializable

data class GetOpenapiJsonDefaultResponse (

    @SerialName(value = "error")
    val error: kotlin.String,

    @SerialName(value = "error_code")
    val errorCode: kotlin.Long? = null

) {


}

