/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack (

    @SerialName(value = "to_key_block")
    val toKeyBlock: kotlin.Boolean,

    @SerialName(value = "from")
    val from: BlockRaw,

    @SerialName(value = "to")
    val to: BlockRaw,

    @SerialName(value = "dest_proof")
    val destProof: kotlin.String,

    @SerialName(value = "proof")
    val proof: kotlin.String,

    @SerialName(value = "state_proof")
    val stateProof: kotlin.String

) {


}

