/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class GetRawAccountState200Response (

    @SerialName(value = "id")
    val id: BlockRaw,

    @SerialName(value = "shardblk")
    val shardblk: BlockRaw,

    @SerialName(value = "shard_proof")
    val shardProof: kotlin.String,

    @SerialName(value = "proof")
    val proof: kotlin.String,

    @SerialName(value = "state")
    val state: kotlin.String

) {


}

