/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: whitelist,graylist,blacklist,none.unknown
 */
@Serializable(with = JettonVerificationTypeSerializer::class)
enum class JettonVerificationType(val value: kotlin.String) {

    @SerialName(value = "whitelist")
    whitelist("whitelist"),

    @SerialName(value = "graylist")
    graylist("graylist"),

    @SerialName(value = "blacklist")
    blacklist("blacklist"),

    @SerialName(value = "none")
    none("none"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is JettonVerificationType) "$data" else null

        /**
         * Returns a valid [JettonVerificationType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): JettonVerificationType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object JettonVerificationTypeSerializer : KSerializer<JettonVerificationType> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): JettonVerificationType {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return JettonVerificationType.entries.firstOrNull { it.value == value }
            ?: JettonVerificationType.unknown
    }

    override fun serialize(encoder: Encoder, value: JettonVerificationType) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

