/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.JettonBridgePrices
import io.tonapi.models.Oracle

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class JettonBridgeParams (

    @SerialName(value = "bridge_address")
    val bridgeAddress: kotlin.String,

    @SerialName(value = "oracles_address")
    val oraclesAddress: kotlin.String,

    @SerialName(value = "state_flags")
    val stateFlags: kotlin.Int,

    @SerialName(value = "oracles")
    val oracles: kotlin.collections.List<Oracle>,

    @SerialName(value = "burn_bridge_fee")
    val burnBridgeFee: kotlin.Long? = null,

    @SerialName(value = "external_chain_address")
    val externalChainAddress: kotlin.String? = null,

    @SerialName(value = "prices")
    val prices: JettonBridgePrices? = null

) {


}

