/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.JettonPreview

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class JettonOperation (

    @SerialName(value = "operation")
    val operation: JettonOperation.Operation,

    @SerialName(value = "utime")
    val utime: kotlin.Long,

    @SerialName(value = "lt")
    val lt: kotlin.Long,

    @SerialName(value = "transaction_hash")
    val transactionHash: kotlin.String,

    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "jetton")
    val jetton: JettonPreview,

    @SerialName(value = "trace_id")
    val traceId: kotlin.String,

    @SerialName(value = "query_id")
    val queryId: kotlin.String,

    @SerialName(value = "source")
    val source: AccountAddress? = null,

    @SerialName(value = "destination")
    val destination: AccountAddress? = null,

    @Contextual @SerialName(value = "payload")
    val payload: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: transfer,mint,burn.unknown
     */
    @Serializable(with = OperationSerializer::class)
    enum class Operation(val value: kotlin.String) {
        @SerialName(value = "transfer") transfer("transfer"),
        @SerialName(value = "mint") mint("mint"),
        @SerialName(value = "burn") burn("burn"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object OperationSerializer : KSerializer<Operation> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Operation {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Operation.entries.firstOrNull { it.value == value }
                ?: Operation.unknown
        }

        override fun serialize(encoder: Encoder, value: Operation) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

