/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.JettonPreview

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class JettonMintAction (

    @SerialName(value = "recipient")
    val recipient: AccountAddress,

    @SerialName(value = "recipients_wallet")
    val recipientsWallet: kotlin.String,

    /* amount in quanta of tokens */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "jetton")
    val jetton: JettonPreview

) {


}

