/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class JettonMetadata (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "symbol")
    val symbol: kotlin.String,

    @SerialName(value = "decimals")
    val decimals: kotlin.String,

    /* this field currently returns a cached image URL (e.g., \"https://cache.tonapi.io/images/jetton.jpg\"). In the future, this will be replaced with the original URL from the metadata. The cached image is already available in the `preview` field of `JettonInfo` and will remain there. */
    @SerialName(value = "image")
    val image: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "social")
    val social: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "websites")
    val websites: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "catalogs")
    val catalogs: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "custom_payload_api_uri")
    val customPayloadApiUri: kotlin.String? = null

) {


}

