/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.TvmStackRecord

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class MethodExecutionResult (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    /* tvm exit code */
    @SerialName(value = "exit_code")
    val exitCode: kotlin.Int,

    @SerialName(value = "stack")
    val stack: kotlin.collections.List<TvmStackRecord>,

    @Contextual @SerialName(value = "decoded")
    val decoded: kotlin.Any? = null

) {


}

