/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class MisbehaviourPunishmentConfig (

    @SerialName(value = "default_flat_fine")
    val defaultFlatFine: kotlin.Long,

    @SerialName(value = "default_proportional_fine")
    val defaultProportionalFine: kotlin.Long,

    @SerialName(value = "severity_flat_mult")
    val severityFlatMult: kotlin.Int,

    @SerialName(value = "severity_proportional_mult")
    val severityProportionalMult: kotlin.Int,

    @SerialName(value = "unpunishable_interval")
    val unpunishableInterval: kotlin.Int,

    @SerialName(value = "long_interval")
    val longInterval: kotlin.Int,

    @SerialName(value = "long_flat_mult")
    val longFlatMult: kotlin.Int,

    @SerialName(value = "long_proportional_mult")
    val longProportionalMult: kotlin.Int,

    @SerialName(value = "medium_interval")
    val mediumInterval: kotlin.Int,

    @SerialName(value = "medium_flat_mult")
    val mediumFlatMult: kotlin.Int,

    @SerialName(value = "medium_proportional_mult")
    val mediumProportionalMult: kotlin.Int

) {


}

