/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class MsgForwardPrices (

    @SerialName(value = "lump_price")
    val lumpPrice: kotlin.Long,

    @SerialName(value = "bit_price")
    val bitPrice: kotlin.Long,

    @SerialName(value = "cell_price")
    val cellPrice: kotlin.Long,

    @SerialName(value = "ihr_price_factor")
    val ihrPriceFactor: kotlin.Long,

    @SerialName(value = "first_frac")
    val firstFrac: kotlin.Long,

    @SerialName(value = "next_frac")
    val nextFrac: kotlin.Long

) {


}

