/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.ImagePreview

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class NftCollection (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "next_item_index")
    val nextItemIndex: kotlin.Long,

    @SerialName(value = "raw_collection_content")
    val rawCollectionContent: kotlin.String,

    @SerialName(value = "approved_by")
    val approvedBy: kotlin.collections.List<NftCollection.ApprovedBy>,

    @SerialName(value = "owner")
    val owner: AccountAddress? = null,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, io.JsonAny>? = null,

    @SerialName(value = "previews")
    val previews: kotlin.collections.List<ImagePreview>? = null

) {

    /**
     * 
     *
     * Values: getgems,tonkeeper.unknown
     */
    @Serializable(with = ApprovedBySerializer::class)
    enum class ApprovedBy(val value: kotlin.String) {
        @SerialName(value = "getgems") getgems("getgems"),
        @SerialName(value = "tonkeeper") tonkeeper("tonkeeper"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object ApprovedBySerializer : KSerializer<ApprovedBy> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): ApprovedBy {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return ApprovedBy.entries.firstOrNull { it.value == value }
                ?: ApprovedBy.unknown
        }

        override fun serialize(encoder: Encoder, value: ApprovedBy) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

