/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.NftItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class NftOperation (

    @SerialName(value = "operation")
    val operation: kotlin.String,

    @SerialName(value = "utime")
    val utime: kotlin.Long,

    @SerialName(value = "lt")
    val lt: kotlin.Long,

    @SerialName(value = "transaction_hash")
    val transactionHash: kotlin.String,

    @SerialName(value = "item")
    val item: NftItem,

    @SerialName(value = "source")
    val source: AccountAddress? = null,

    @SerialName(value = "destination")
    val destination: AccountAddress? = null

) {


}

