/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.Oracle

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class OracleBridgeParams (

    @SerialName(value = "bridge_addr")
    val bridgeAddr: kotlin.String,

    @SerialName(value = "oracle_multisig_address")
    val oracleMultisigAddress: kotlin.String,

    @SerialName(value = "external_chain_address")
    val externalChainAddress: kotlin.String,

    @SerialName(value = "oracles")
    val oracles: kotlin.collections.List<Oracle>

) {


}

