/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: whales,tf,liquidTF.unknown
 */
@Serializable(with = PoolImplementationTypeSerializer::class)
enum class PoolImplementationType(val value: kotlin.String) {

    @SerialName(value = "whales")
    whales("whales"),

    @SerialName(value = "tf")
    tf("tf"),

    @SerialName(value = "liquidTF")
    liquidTF("liquidTF"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PoolImplementationType) "$data" else null

        /**
         * Returns a valid [PoolImplementationType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PoolImplementationType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object PoolImplementationTypeSerializer : KSerializer<PoolImplementationType> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): PoolImplementationType {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return PoolImplementationType.entries.firstOrNull { it.value == value }
            ?: PoolImplementationType.unknown
    }

    override fun serialize(encoder: Encoder, value: PoolImplementationType) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

