/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.PoolImplementationType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class PoolInfo (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "total_amount")
    val totalAmount: kotlin.Long,

    @Contextual @SerialName(value = "implementation")
    val implementation: PoolImplementationType,

    /* APY in percent */
    @SerialName(value = "apy")
    val apy: kotlin.String,

    @SerialName(value = "min_stake")
    val minStake: kotlin.Long,

    /* current nomination cycle beginning timestamp */
    @SerialName(value = "cycle_start")
    val cycleStart: kotlin.Long,

    /* current nomination cycle ending timestamp */
    @SerialName(value = "cycle_end")
    val cycleEnd: kotlin.Long,

    /* this pool has verified source code or managed by trusted company */
    @SerialName(value = "verified")
    val verified: kotlin.Boolean,

    /* current number of nominators */
    @SerialName(value = "current_nominators")
    val currentNominators: kotlin.Int,

    /* maximum number of nominators */
    @SerialName(value = "max_nominators")
    val maxNominators: kotlin.Int,

    /* total stake of all nominators */
    @SerialName(value = "nominators_stake")
    val nominatorsStake: kotlin.Long,

    /* stake of validator */
    @SerialName(value = "validator_stake")
    val validatorStake: kotlin.Long,

    /* for liquid staking master account of jetton */
    @SerialName(value = "liquid_jetton_master")
    val liquidJettonMaster: kotlin.String? = null,

    @SerialName(value = "cycle_length")
    val cycleLength: kotlin.Long? = null

) {


}

