/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.CurrencyType
import io.tonapi.models.TrustType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Price (

    @Contextual @SerialName(value = "currency_type")
    val currencyType: CurrencyType,

    @SerialName(value = "value")
    val `value`: kotlin.String,

    @SerialName(value = "decimals")
    val decimals: kotlin.Int,

    @SerialName(value = "token_name")
    val tokenName: kotlin.String,

    @Contextual @SerialName(value = "verification")
    val verification: TrustType,

    @SerialName(value = "image")
    val image: kotlin.String,

    @SerialName(value = "jetton")
    val jetton: kotlin.String? = null

) {


}

