/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.Metadata
import io.tonapi.models.Price

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Purchase (

    @SerialName(value = "event_id")
    val eventId: kotlin.String,

    @SerialName(value = "invoice_id")
    val invoiceId: kotlin.String,

    @SerialName(value = "source")
    val source: AccountAddress,

    @SerialName(value = "destination")
    val destination: AccountAddress,

    @SerialName(value = "lt")
    val lt: kotlin.Long,

    @SerialName(value = "utime")
    val utime: kotlin.Long,

    @SerialName(value = "amount")
    val amount: Price,

    @SerialName(value = "metadata")
    val metadata: Metadata

) {


}

