/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class ReducedBlock (

    @SerialName(value = "workchain_id")
    val workchainId: kotlin.Int,

    @SerialName(value = "shard")
    val shard: kotlin.String,

    @SerialName(value = "seqno")
    val seqno: kotlin.Int,

    @SerialName(value = "tx_quantity")
    val txQuantity: kotlin.Int,

    @SerialName(value = "utime")
    val utime: kotlin.Long,

    @SerialName(value = "shards_blocks")
    val shardsBlocks: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "parent")
    val parent: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "master_ref")
    val masterRef: kotlin.String? = null

) {


}

