/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class SendBlockchainMessageRequest (

    @SerialName(value = "boc")
    val boc: kotlin.String? = null,

    @SerialName(value = "batch")
    val batch: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "meta")
    val meta: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

