/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class ServiceStatus (

    @SerialName(value = "rest_online")
    val restOnline: kotlin.Boolean = true,

    @SerialName(value = "indexing_latency")
    val indexingLatency: kotlin.Int,

    @SerialName(value = "last_known_masterchain_seqno")
    val lastKnownMasterchainSeqno: kotlin.Int

) {


}

