/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.MessageConsequences
import io.tonapi.models.SignRawMessage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class SignRawParams (

    @SerialName(value = "protocol_name")
    val protocolName: kotlin.String,

    @SerialName(value = "relay_address")
    val relayAddress: kotlin.String,

    /* Commission for the transaction. In nanocoins. */
    @SerialName(value = "commission")
    val commission: kotlin.String,

    @SerialName(value = "from")
    val from: kotlin.String,

    @SerialName(value = "valid_until")
    val validUntil: kotlin.Long,

    @SerialName(value = "messages")
    val messages: kotlin.collections.List<SignRawMessage>,

    @SerialName(value = "emulation")
    val emulation: MessageConsequences? = null

) {


}

