/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.Refund

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class SmartContractAction (

    @SerialName(value = "executor")
    val executor: AccountAddress,

    @SerialName(value = "contract")
    val `contract`: AccountAddress,

    /* amount in nanotons */
    @SerialName(value = "ton_attached")
    val tonAttached: kotlin.Long,

    @SerialName(value = "operation")
    val operation: kotlin.String,

    @SerialName(value = "payload")
    val payload: kotlin.String? = null,

    @SerialName(value = "refund")
    val refund: Refund? = null

) {


}

