/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class StorageProvider (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "accept_new_contracts")
    val acceptNewContracts: kotlin.Boolean,

    @SerialName(value = "rate_per_mb_day")
    val ratePerMbDay: kotlin.Long,

    @SerialName(value = "max_span")
    val maxSpan: kotlin.Long,

    @SerialName(value = "minimal_file_size")
    val minimalFileSize: kotlin.Long,

    @SerialName(value = "maximal_file_size")
    val maximalFileSize: kotlin.Long

) {


}

