/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.Metadata
import io.tonapi.models.Price

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Subscription (

    /* type of subscription */
    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "status")
    val status: Subscription.Status,

    /* payment period in seconds */
    @SerialName(value = "period")
    val period: kotlin.Long,

    /* common identifier */
    @SerialName(value = "subscription_id")
    val subscriptionId: kotlin.String,

    @SerialName(value = "payment_per_period")
    val paymentPerPeriod: Price,

    @SerialName(value = "wallet")
    val wallet: AccountAddress,

    @SerialName(value = "next_charge_at")
    val nextChargeAt: kotlin.Long,

    @SerialName(value = "metadata")
    val metadata: Metadata,

    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "beneficiary")
    val beneficiary: AccountAddress? = null,

    @SerialName(value = "admin")
    val admin: AccountAddress? = null

) {

    /**
     * 
     *
     * Values: not_ready,active,suspended,cancelled.unknown
     */
    @Serializable(with = StatusSerializer::class)
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "not_ready") not_ready("not_ready"),
        @SerialName(value = "active") active("active"),
        @SerialName(value = "suspended") suspended("suspended"),
        @SerialName(value = "cancelled") cancelled("cancelled"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object StatusSerializer : KSerializer<Status> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Status {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Status.entries.firstOrNull { it.value == value }
                ?: Status.unknown
        }

        override fun serialize(encoder: Encoder, value: Status) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

