/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.Price

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class SubscriptionAction (

    @SerialName(value = "subscriber")
    val subscriber: AccountAddress,

    @SerialName(value = "subscription")
    val subscription: kotlin.String,

    @SerialName(value = "beneficiary")
    val beneficiary: AccountAddress,

    @SerialName(value = "admin")
    val admin: AccountAddress,

    @SerialName(value = "price")
    val price: Price,

    @SerialName(value = "initial")
    val initial: kotlin.Boolean,

    @SerialName(value = "amount")
    @Deprecated(message = "This property is deprecated.")
    val amount: kotlin.Long? = null

) {


}

