/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class TokenRates (

    @SerialName(value = "prices")
    val prices: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "diff_24h")
    val diff24h: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "diff_7d")
    val diff7d: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "diff_30d")
    val diff30d: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

