/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.TonConnectProofRequestProofDomain

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class TonConnectProofRequestProof (

    @SerialName(value = "timestamp")
    val timestamp: kotlin.Long,

    @SerialName(value = "domain")
    val domain: TonConnectProofRequestProofDomain,

    @SerialName(value = "signature")
    val signature: kotlin.String,

    @SerialName(value = "payload")
    val payload: kotlin.String,

    @SerialName(value = "state_init")
    val stateInit: kotlin.String? = null

) {


}

