/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.AccountStatus
import io.tonapi.models.ActionPhase
import io.tonapi.models.BouncePhaseType
import io.tonapi.models.ComputePhase
import io.tonapi.models.CreditPhase
import io.tonapi.models.Message
import io.tonapi.models.StoragePhase
import io.tonapi.models.TransactionType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Transaction (

    @SerialName(value = "hash")
    val hash: kotlin.String,

    @SerialName(value = "lt")
    val lt: kotlin.Long,

    @SerialName(value = "account")
    val account: AccountAddress,

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "utime")
    val utime: kotlin.Long,

    @Contextual @SerialName(value = "orig_status")
    val origStatus: AccountStatus,

    @Contextual @SerialName(value = "end_status")
    val endStatus: AccountStatus,

    @SerialName(value = "total_fees")
    val totalFees: kotlin.Long,

    @SerialName(value = "end_balance")
    val endBalance: kotlin.Long,

    @Contextual @SerialName(value = "transaction_type")
    val transactionType: TransactionType,

    @SerialName(value = "state_update_old")
    val stateUpdateOld: kotlin.String,

    @SerialName(value = "state_update_new")
    val stateUpdateNew: kotlin.String,

    @SerialName(value = "out_msgs")
    val outMsgs: kotlin.collections.List<Message>,

    @SerialName(value = "block")
    val block: kotlin.String,

    @SerialName(value = "aborted")
    val aborted: kotlin.Boolean,

    @SerialName(value = "destroyed")
    val destroyed: kotlin.Boolean,

    /* hex encoded boc with raw transaction */
    @SerialName(value = "raw")
    val raw: kotlin.String,

    @SerialName(value = "in_msg")
    val inMsg: Message? = null,

    @SerialName(value = "prev_trans_hash")
    val prevTransHash: kotlin.String? = null,

    @SerialName(value = "prev_trans_lt")
    val prevTransLt: kotlin.Long? = null,

    @SerialName(value = "compute_phase")
    val computePhase: ComputePhase? = null,

    @SerialName(value = "storage_phase")
    val storagePhase: StoragePhase? = null,

    @SerialName(value = "credit_phase")
    val creditPhase: CreditPhase? = null,

    @SerialName(value = "action_phase")
    val actionPhase: ActionPhase? = null,

    @Contextual @SerialName(value = "bounce_phase")
    val bouncePhase: BouncePhaseType? = null

) {


}

