/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: TransOrd,TransTickTock,TransSplitPrepare,TransSplitInstall,TransMergePrepare,TransMergeInstall,TransStorage.unknown
 */
@Serializable(with = TransactionTypeSerializer::class)
enum class TransactionType(val value: kotlin.String) {

    @SerialName(value = "TransOrd")
    TransOrd("TransOrd"),

    @SerialName(value = "TransTickTock")
    TransTickTock("TransTickTock"),

    @SerialName(value = "TransSplitPrepare")
    TransSplitPrepare("TransSplitPrepare"),

    @SerialName(value = "TransSplitInstall")
    TransSplitInstall("TransSplitInstall"),

    @SerialName(value = "TransMergePrepare")
    TransMergePrepare("TransMergePrepare"),

    @SerialName(value = "TransMergeInstall")
    TransMergeInstall("TransMergeInstall"),

    @SerialName(value = "TransStorage")
    TransStorage("TransStorage"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TransactionType) "$data" else null

        /**
         * Returns a valid [TransactionType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TransactionType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object TransactionTypeSerializer : KSerializer<TransactionType> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): TransactionType {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return TransactionType.entries.firstOrNull { it.value == value }
            ?: TransactionType.unknown
    }

    override fun serialize(encoder: Encoder, value: TransactionType) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

