/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class TvmStackRecord (

    @SerialName(value = "type")
    val type: TvmStackRecord.Type,

    @SerialName(value = "cell")
    val cell: kotlin.String? = null,

    @SerialName(value = "slice")
    val slice: kotlin.String? = null,

    @SerialName(value = "num")
    val num: kotlin.String? = null,

    @SerialName(value = "tuple")
    val tuple: kotlin.collections.List<TvmStackRecord>? = null

) {

    /**
     * 
     *
     * Values: cell,num,nan,`null`,tuple.unknown
     */
    @Serializable(with = TypeSerializer::class)
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "cell") cell("cell"),
        @SerialName(value = "num") num("num"),
        @SerialName(value = "nan") nan("nan"),
        @SerialName(value = "null") `null`("null"),
        @SerialName(value = "tuple") tuple("tuple"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object TypeSerializer : KSerializer<Type> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Type {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Type.entries.firstOrNull { it.value == value }
                ?: Type.unknown
        }

        override fun serialize(encoder: Encoder, value: Type) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

