/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.Validator

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Validators (

    @SerialName(value = "elect_at")
    val electAt: kotlin.Long,

    @SerialName(value = "elect_close")
    val electClose: kotlin.Long,

    @SerialName(value = "min_stake")
    val minStake: kotlin.Long,

    @SerialName(value = "total_stake")
    val totalStake: kotlin.Long,

    @SerialName(value = "validators")
    val validators: kotlin.collections.List<Validator>

) {


}

