/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.ValidatorsSetListInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class ValidatorsSet (

    @SerialName(value = "utime_since")
    val utimeSince: kotlin.Int,

    @SerialName(value = "utime_until")
    val utimeUntil: kotlin.Int,

    @SerialName(value = "total")
    val total: kotlin.Int,

    @SerialName(value = "main")
    val main: kotlin.Int,

    @SerialName(value = "list")
    val list: kotlin.collections.List<ValidatorsSetListInner>,

    @SerialName(value = "total_weight")
    val totalWeight: kotlin.String? = null

) {


}

