/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.ValueFlowJettonsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class ValueFlow (

    @SerialName(value = "account")
    val account: AccountAddress,

    @SerialName(value = "ton")
    val ton: kotlin.Long,

    @SerialName(value = "fees")
    val fees: kotlin.Long,

    @SerialName(value = "jettons")
    val jettons: kotlin.collections.List<ValueFlowJettonsInner>? = null

) {


}

