/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class WalletStats (

    @SerialName(value = "nfts_count")
    val nftsCount: kotlin.Int,

    @SerialName(value = "jettons_count")
    val jettonsCount: kotlin.Int,

    @SerialName(value = "multisig_count")
    val multisigCount: kotlin.Int,

    @SerialName(value = "staking_count")
    val stakingCount: kotlin.Int

) {


}

