/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class WorkchainDescr (

    @SerialName(value = "workchain")
    val workchain: kotlin.Int,

    @SerialName(value = "enabled_since")
    val enabledSince: kotlin.Long,

    @SerialName(value = "actual_min_split")
    val actualMinSplit: kotlin.Int,

    @SerialName(value = "min_split")
    val minSplit: kotlin.Int,

    @SerialName(value = "max_split")
    val maxSplit: kotlin.Int,

    @SerialName(value = "basic")
    val basic: kotlin.Int,

    @SerialName(value = "active")
    val active: kotlin.Boolean,

    @SerialName(value = "accept_msgs")
    val acceptMsgs: kotlin.Boolean,

    @SerialName(value = "flags")
    val flags: kotlin.Int,

    @SerialName(value = "zerostate_root_hash")
    val zerostateRootHash: kotlin.String,

    @SerialName(value = "zerostate_file_hash")
    val zerostateFileHash: kotlin.String,

    @SerialName(value = "version")
    val version: kotlin.Long

) {


}

