package network.tos.blockchain.ton.contract

import org.junit.Assert.*
import org.junit.Test
import org.ton.block.AddrStd
import org.ton.cell.Cell
import org.ton.cell.buildCell
import org.ton.crypto.hex

class TosQuantumAuthTest {
    private fun hash(n: Int) = ByteArray(32).also { it[31] = n.toByte() }
    private fun request(role: QuantumAuthRole, action: QuantumAuthAction = QuantumAuthAction.Execute(Cell.empty())) =
        TosQuantumAuth(42, hash(123), AddrStd(0, hash(100)), AddrStd(0, hash(101)), role, 1u, 0u, 1780000600, action, 1780000000)
    private fun send(mode: Int, previous: Cell = Cell.empty(), tag: Long = 0x0ec3c86d) =
        buildCell { storeUInt(tag, 32); storeUInt(mode, 8); storeRef(previous); storeRef(Cell.empty()) }

    @Test fun independentPrimaryAndRescueExecuteVectors() {
        // Fixed Python/Rust vectors, not values generated by this encoder.
        val expected = listOf(
            Triple(QuantumAuthRole.PRIMARY, "b42018426236198dd5be93d0300bcaf161d29c1b22727951e2891f5d6b019eec", "80f53e05a27dbb286952aa8a23c134a2daa0cea93f64285fdd931b5db92e89d2"),
            Triple(QuantumAuthRole.RESCUE, "de815703739699e50580272c84495b7964faf411d50dc03db79e48230e3e18a8", "60fb1d06134c90f95acc876ab25ea3fd391abc731e23527744bc7128d617e57f")
        )
        for ((role, digest, submission) in expected) {
            val r = request(role)
            assertArrayEquals(hex(digest), r.digest)
            assertArrayEquals(hex(submission), r.submission(ByteArray(role.signatureSize) { 0xa5.toByte() }).hash().toByteArray())
            r.digest.fill(0); assertArrayEquals(hex(digest), r.digest)
        }
    }
    @Test fun allModeBytesOldestActionAndCountBoundaries() {
        val allowed = setOf(2, 3, 18, 19, 66, 67, 82, 83, 130, 131, 146, 147)
        for (mode in 0..255) assertEquals("mode $mode", allowed.contains(mode), runCatching { TosQuantumAuth.validateActions(send(mode)) }.isSuccess)
        assertTrue(runCatching { TosQuantumAuth.validateActions(send(3, send(32))) }.exceptionOrNull() is IllegalArgumentException)
        var list = Cell.empty()
        for (count in 0..256) {
            assertEquals("count $count", count <= 255, runCatching { TosQuantumAuth.validateActions(list) }.isSuccess)
            list = send(3, list)
        }
        for (tag in listOf(0xad4de08eL, 0x36e6b809L, 0L)) assertTrue(runCatching { TosQuantumAuth.validateActions(send(3, tag = tag)) }.isFailure)
    }
    @Test fun primaryControlsAndClassicalSignatureRejected() {
        for (action in listOf(QuantumAuthAction.Configure(), QuantumAuthAction.LockPrimary,
            QuantumAuthAction.Migrate(Cell.empty(), Cell.empty(), Cell.empty()))) {
            assertEquals("PRIMARY may only execute", runCatching { request(QuantumAuthRole.PRIMARY, action) }.exceptionOrNull()?.message)
            request(QuantumAuthRole.RESCUE, action)
        }
        for (role in QuantumAuthRole.entries) {
            val r = request(role)
            for (size in listOf(64, role.signatureSize - 1, role.signatureSize + 1))
                assertEquals("Wrong PQ signature length", runCatching { r.submission(ByteArray(size)) }.exceptionOrNull()?.message)
        }
    }
    @Test fun allIndependentActionVectors() {
        fun tag(n: Long) = buildCell { storeUInt(n, 8) }
        run {
            val r = request(QuantumAuthRole.PRIMARY, QuantumAuthAction.Execute(Cell.empty()))
            assertArrayEquals(hex("117829e21b72b6e2041f15c92b4b1276ef05ccf5a90fe4f1fa65de76c16f2a19"), r.request.hash().toByteArray())
            assertArrayEquals(hex("b42018426236198dd5be93d0300bcaf161d29c1b22727951e2891f5d6b019eec"), r.digest)
            assertArrayEquals(hex("80f53e05a27dbb286952aa8a23c134a2daa0cea93f64285fdd931b5db92e89d2"), r.submission(ByteArray(r.role.signatureSize) { 0xa5.toByte() }).hash().toByteArray())
        }
        run {
            val r = request(QuantumAuthRole.RESCUE, QuantumAuthAction.Execute(Cell.empty()))
            assertArrayEquals(hex("4525eb377a604bd438d0e5d7233ea52de59c0c13eebea823c6926f784aad4eba"), r.request.hash().toByteArray())
            assertArrayEquals(hex("de815703739699e50580272c84495b7964faf411d50dc03db79e48230e3e18a8"), r.digest)
            assertArrayEquals(hex("60fb1d06134c90f95acc876ab25ea3fd391abc731e23527744bc7128d617e57f"), r.submission(ByteArray(r.role.signatureSize) { 0xa5.toByte() }).hash().toByteArray())
        }
        run {
            val r = request(QuantumAuthRole.RESCUE, QuantumAuthAction.Configure())
            assertArrayEquals(hex("8478f4270ceb1ce10c7332073178519962d17b634acacd9f3e58191d3b6a501e"), r.request.hash().toByteArray())
            assertArrayEquals(hex("e2a61220523035e212549a1ee678ba9b61de25c582328e8a89eed97cfc2a3e0b"), r.digest)
            assertArrayEquals(hex("e972db3559cc28c274d4bf1b7dbb249aa7c603adfb1bbed01d59300f10b459b9"), r.submission(ByteArray(r.role.signatureSize) { 0xa5.toByte() }).hash().toByteArray())
        }
        run {
            val r = request(QuantumAuthRole.RESCUE, QuantumAuthAction.Configure(tag(1) to tag(2)))
            assertArrayEquals(hex("4217b0148d1199ebb9ac1a4fdcf5bb63d3abd4f24d245ea89192a68d7257d47e"), r.request.hash().toByteArray())
            assertArrayEquals(hex("6ae034de5cae60c1bda9ca1d72ecfdddf70f6fad20736d0ebef05c2c053adddf"), r.digest)
            assertArrayEquals(hex("414d363db59bdbb6145cc138dbd9d2e7fc731bb08a7638effa68348d2937ea40"), r.submission(ByteArray(r.role.signatureSize) { 0xa5.toByte() }).hash().toByteArray())
        }
        run {
            val r = request(QuantumAuthRole.RESCUE, QuantumAuthAction.LockPrimary)
            assertArrayEquals(hex("19b4696476903df28fae6e810cd21bdf043c0b332f6bfa5ff9fcb3c101a8aa86"), r.request.hash().toByteArray())
            assertArrayEquals(hex("e57eeede14e3f2e78753c017661c59de915c9e94b0d28da9ef5d58881fae4327"), r.digest)
            assertArrayEquals(hex("86595892c9af65a91f2db90912c68004f9c36dee36beb5029ff73824938323a4"), r.submission(ByteArray(r.role.signatureSize) { 0xa5.toByte() }).hash().toByteArray())
        }
        run {
            val r = request(QuantumAuthRole.RESCUE, QuantumAuthAction.Migrate(tag(1), tag(2), tag(3)))
            assertArrayEquals(hex("f4d8f32b1bcb1f2ed8e2e6956cfd40870492df9a04584a27a3eb7577f7d9a6bc"), r.request.hash().toByteArray())
            assertArrayEquals(hex("d060c9abb3a571cee1fe2121676d8cb394e61c7a59ced5ac01d7cd1aa2ae5e08"), r.digest)
            assertArrayEquals(hex("91517376b5dda01ee0e144073eb1c4f46aa88762a04484a1058ecff6926f00ab"), r.submission(ByteArray(r.role.signatureSize) { 0xa5.toByte() }).hash().toByteArray())
        }
    }
}
