package network.tos.blockchain.ton.contract

import org.junit.Assert.*
import org.junit.Test
import org.ton.block.AddrStd
import org.ton.cell.Cell
import org.ton.cell.buildCell
import org.ton.crypto.hex

class TosV5R2AuthTest {
    private fun hash(n: Int) = ByteArray(32).also { it[31] = n.toByte() }
    private fun request(role: V5R2AuthRole, action: V5R2AuthAction = V5R2AuthAction.Execute(Cell.empty())) =
        TosV5R2Auth(42, hash(123), AddrStd(0, hash(100)), AddrStd(0, hash(101)), role, 1u, 0u, 1780000600, action, 1780000000)
    private fun send(mode: Int, previous: Cell = Cell.empty(), tag: Long = 0x0ec3c86d) =
        buildCell { storeUInt(tag, 32); storeUInt(mode, 8); storeRef(previous); storeRef(Cell.empty()) }

    @Test fun independentPrimaryAndRescueExecuteVectors() {
        // Fixed Python/Rust vectors, not values generated by this encoder.
        val expected = listOf(
            Triple(V5R2AuthRole.PRIMARY, "b42018426236198dd5be93d0300bcaf161d29c1b22727951e2891f5d6b019eec", "80f53e05a27dbb286952aa8a23c134a2daa0cea93f64285fdd931b5db92e89d2"),
            Triple(V5R2AuthRole.RESCUE, "de815703739699e50580272c84495b7964faf411d50dc03db79e48230e3e18a8", "60fb1d06134c90f95acc876ab25ea3fd391abc731e23527744bc7128d617e57f")
        )
        for ((role, digest, submission) in expected) {
            val r = request(role)
            assertArrayEquals(hex(digest), r.digest)
            assertArrayEquals(hex(submission), r.submission(ByteArray(role.signatureSize) { 0xa5.toByte() }).hash().toByteArray())
            r.digest.fill(0); assertArrayEquals(hex(digest), r.digest)
        }
    }
    @Test fun allModeBytesOldestActionAndCountBoundaries() {
        val allowed = setOf(2, 3, 18, 19, 66, 67, 82, 83, 130, 131, 146, 147)
        for (mode in 0..255) assertEquals("mode $mode", allowed.contains(mode), runCatching { TosV5R2Auth.validateActions(send(mode)) }.isSuccess)
        assertTrue(runCatching { TosV5R2Auth.validateActions(send(3, send(32))) }.exceptionOrNull() is IllegalArgumentException)
        var list = Cell.empty()
        for (count in 0..256) {
            assertEquals("count $count", count <= 255, runCatching { TosV5R2Auth.validateActions(list) }.isSuccess)
            list = send(3, list)
        }
        for (tag in listOf(0xad4de08eL, 0x36e6b809L, 0L)) assertTrue(runCatching { TosV5R2Auth.validateActions(send(3, tag = tag)) }.isFailure)
    }
    @Test fun primaryControlsAndClassicalSignatureRejected() {
        for (action in listOf(V5R2AuthAction.Configure(), V5R2AuthAction.LockPrimary,
            V5R2AuthAction.Migrate(Cell.empty(), Cell.empty(), Cell.empty()))) {
            assertEquals("PRIMARY may only execute", runCatching { request(V5R2AuthRole.PRIMARY, action) }.exceptionOrNull()?.message)
            request(V5R2AuthRole.RESCUE, action)
        }
        for (role in V5R2AuthRole.entries) {
            val r = request(role)
            for (size in listOf(64, role.signatureSize - 1, role.signatureSize + 1))
                assertEquals("Wrong PQ signature length", runCatching { r.submission(ByteArray(size)) }.exceptionOrNull()?.message)
        }
    }
}
