/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class AndroidBatteryPurchaseStatusPurchasesInnerError (

    @SerialName(value = "msg")
    val msg: kotlin.String,

    @SerialName(value = "code")
    val code: AndroidBatteryPurchaseStatusPurchasesInnerError.Code

) {

    /**
     * 
     *
     * Values: invalidMinusProductMinusId,userMinusNotMinusFound,purchaseMinusIsMinusAlreadyMinusUsed,temporaryMinusError,unknown.unknown
     */
    @Serializable(with = CodeSerializer::class)
    enum class Code(val value: kotlin.String) {
        @SerialName(value = "invalid-product-id") invalidMinusProductMinusId("invalid-product-id"),
        @SerialName(value = "user-not-found") userMinusNotMinusFound("user-not-found"),
        @SerialName(value = "purchase-is-already-used") purchaseMinusIsMinusAlreadyMinusUsed("purchase-is-already-used"),
        @SerialName(value = "temporary-error") temporaryMinusError("temporary-error"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object CodeSerializer : KSerializer<Code> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Code {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Code.entries.firstOrNull { it.value == value }
                ?: Code.unknown
        }

        override fun serialize(encoder: Encoder, value: Code) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

