/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class Balance (

    @SerialName(value = "balance")
    val balance: kotlin.String,

    /* reserved amount in units (TON/USD) */
    @SerialName(value = "reserved")
    val reserved: kotlin.String,

    @SerialName(value = "units")
    val units: Balance.Units

) {

    /**
     * 
     *
     * Values: usd,ton.unknown
     */
    @Serializable(with = UnitsSerializer::class)
    enum class Units(val value: kotlin.String) {
        @SerialName(value = "usd") usd("usd"),
        @SerialName(value = "ton") ton("ton"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object UnitsSerializer : KSerializer<Units> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Units {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Units.entries.firstOrNull { it.value == value }
                ?: Units.unknown
        }

        override fun serialize(encoder: Encoder, value: Units) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

