/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class ConfigMeanPrices (

    @SerialName(value = "battery_mean_price_swap")
    val batteryMeanPriceSwap: kotlin.Int,

    @SerialName(value = "battery_mean_price_jetton")
    val batteryMeanPriceJetton: kotlin.Int,

    @SerialName(value = "battery_mean_price_nft")
    val batteryMeanPriceNft: kotlin.Int,

    @SerialName(value = "battery_mean_price_tron_usdt")
    val batteryMeanPriceTronUsdt: kotlin.Int? = null,

    @SerialName(value = "ton_mean_price_tron_usdt")
    val tonMeanPriceTronUsdt: kotlin.Float? = null

) {


}

