/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.EstimatedTronTxInstantFee

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class EstimatedTronTx (

    @SerialName(value = "energy_charges")
    val energyCharges: kotlin.Int,

    @SerialName(value = "bandwidth_charges")
    val bandwidthCharges: kotlin.Int,

    @SerialName(value = "activation_charges")
    val activationCharges: kotlin.Int,

    @SerialName(value = "total_charges")
    val totalCharges: kotlin.Int,

    @SerialName(value = "instant_fee")
    val instantFee: EstimatedTronTxInstantFee

) {


}

