/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class EstimatedTronTxInstantFeeAcceptedAssetsInner (

    @SerialName(value = "type")
    val type: EstimatedTronTxInstantFeeAcceptedAssetsInner.Type,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "amount_nano")
    val amountNano: kotlin.String,

    @SerialName(value = "decimals")
    val decimals: kotlin.Int,

    @SerialName(value = "jetton_master_id")
    val jettonMasterId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: jetton,ton.unknown
     */
    @Serializable(with = TypeSerializer::class)
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "jetton") jetton("jetton"),
        @SerialName(value = "ton") ton("ton"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object TypeSerializer : KSerializer<Type> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Type {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Type.entries.firstOrNull { it.value == value }
                ?: Type.unknown
        }

        override fun serialize(encoder: Encoder, value: Type) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

