/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class InlineObject (

    @SerialName(value = "error")
    val error: kotlin.String,

    @SerialName(value = "error-key")
    val errorKey: kotlin.String? = null,

    @SerialName(value = "error-details")
    val errorDetails: kotlin.String? = null

) {


}

