/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.IOSBatteryPurchaseStatusTransactionsInnerError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class IOSBatteryPurchaseStatusTransactionsInner (

    @SerialName(value = "transaction_id")
    val transactionId: kotlin.String,

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "error")
    val error: IOSBatteryPurchaseStatusTransactionsInnerError? = null

) {


}

