/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.PurchasesPurchasesInnerRefundInformationRefunded

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class PurchasesPurchasesInnerRefundInformation (

    @SerialName(value = "fully_refunded")
    val fullyRefunded: kotlin.Boolean,

    @SerialName(value = "partially_refunded")
    val partiallyRefunded: kotlin.Boolean,

    @SerialName(value = "pending_refund")
    val pendingRefund: kotlin.Boolean,

    @SerialName(value = "refunded")
    val refunded: PurchasesPurchasesInnerRefundInformationRefunded? = null,

    @SerialName(value = "refundable")
    val refundable: PurchasesPurchasesInnerRefundInformationRefunded? = null

) {


}

