/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.PurchasesPurchasesInnerRefundInformation

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class PurchasesPurchasesInner (

    @SerialName(value = "user_purchase_id")
    @Deprecated(message = "This property is deprecated.")
    val userPurchaseId: kotlin.Int,

    @SerialName(value = "purchase_id")
    val purchaseId: kotlin.Int,

    @SerialName(value = "type")
    val type: PurchasesPurchasesInner.Type,

    @SerialName(value = "charges")
    val charges: kotlin.Int,

    @SerialName(value = "datetime")
    val datetime: kotlin.String,

    @SerialName(value = "promo")
    val promo: kotlin.String? = null,

    @SerialName(value = "for_account_id")
    val forAccountId: kotlin.String? = null,

    /* Amount describes the amount paid by the user for this purchase when we know it. For crypto purchases it is always set. */
    @SerialName(value = "amount")
    val amount: kotlin.String? = null,

    /* Currency is set when we know it. For crypto purchases it is always set. */
    @SerialName(value = "currency")
    val currency: kotlin.String? = null,

    @SerialName(value = "refund_information")
    val refundInformation: PurchasesPurchasesInnerRefundInformation? = null

) {

    /**
     * 
     *
     * Values: android,ios,promoMinusCode,crypto,gift,onMinusTheMinusWayMinusGift.unknown
     */
    @Serializable(with = TypeSerializer::class)
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "android") android("android"),
        @SerialName(value = "ios") ios("ios"),
        @SerialName(value = "promo-code") promoMinusCode("promo-code"),
        @SerialName(value = "crypto") crypto("crypto"),
        @SerialName(value = "gift") gift("gift"),
        @SerialName(value = "on-the-way-gift") onMinusTheMinusWayMinusGift("on-the-way-gift"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object TypeSerializer : KSerializer<Type> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Type {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Type.entries.firstOrNull { it.value == value }
                ?: Type.unknown
        }

        override fun serialize(encoder: Encoder, value: Type) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

