/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class TransactionsTransactionsInner (

    @SerialName(value = "id")
    val id: kotlin.String,

    /* represents the amount of money paid by the user for this transaction. */
    @SerialName(value = "paid_amount")
    val paidAmount: kotlin.String,

    @SerialName(value = "status")
    val status: TransactionsTransactionsInner.Status,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String

) {

    /**
     * 
     *
     * Values: pending,completed,failed.unknown
     */
    @Serializable(with = StatusSerializer::class)
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "completed") completed("completed"),
        @SerialName(value = "failed") failed("failed"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object StatusSerializer : KSerializer<Status> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Status {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Status.entries.firstOrNull { it.value == value }
                ?: Status.unknown
        }

        override fun serialize(encoder: Encoder, value: Status) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

