name: Android APK release CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: apk-release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Decode signing certificate into a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.ANDROID_DIST_SIGNING_KEY }}
        run: |
          printf '%s' "$CERTIFICATE_BASE64" | base64 --decode > google-release.keystore

      - name: Build signed release artifacts
        run: |
          ./gradlew :apps:wallet:instance:main:assembleSiteRelease \
            -Pandroid.injected.signing.store.file="$KEYSTORE_FILE" \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD" \
            -PisApk=true
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/google-release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.TOS_UPLOAD_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.TOS_UPLOAD_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.TOS_UPLOAD_KEY_PASSWORD }}

      - name: Upload android apk to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TOS-Wallet-${{ github.ref_name }}-apk
          path: apps/wallet/instance/main/build/outputs/apk/site/release/main-site-release.apk

      - name: Fix filename
        run: |
          mkdir -p release
          cp apps/wallet/instance/main/build/outputs/apk/site/release/main-site-release.apk release/TOS-Wallet.apk

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: release/TOS-Wallet.apk

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with: { name: apk }

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: TOS-Wallet.apk
          generate_release_notes: true
